### ISSUE TITLE
tf does real hitbox do?

### ISSUE THREAD

**Issue by Sxnpaiwin** [NoobLikesThis/roblox-fflags#1]

**Comment by NoobLikesThis** [comment]
not sure, could be a hitbox expander at this point bc ik it changes hitboxes

**Comment by NoobLikesThis** [comment]
btw i might put u as my first person to be here

**Comment by ucjd** [comment]
correct, it is a hitbox expander i was very suprised to see this here as i seen it one time in a youtubers vid exposing someone for using cheats he said it was a hitbox expander 😭

**Comment by NoobLikesThis** [comment]
wow
