### ISSUE TITLE
"FFlagTaskSchedulerLimitTargetFpsTo2402": "False" forces roblox to open in background mode

### ISSUE THREAD

**Issue by Soupplex** [NoobLikesThis/roblox-fflags#10]
How do i fix this?

**Comment by NoobLikesThis** [comment]
background mode?
idk what that means

**Comment by Soupplex** [comment]
> background mode? idk what that means

I will explain.When i launch Roblox with this fast flag.It opens...But!No active roblox window appears.I checked task manager and...Roblox there.No active window or anything.When i delete this fast flag,Roblox window will appear when i launch it.So how do i fix this?I just wanna have "unlimited FPS unlocker"

**Comment by Soupplex** [comment]
You commented really late NGL.

**Comment by NoobLikesThis** [comment]
use a diff rendering mode like opengl or vulkan

**Comment by Soupplex** [comment]
Other methods?

**Comment by NoobLikesThis** [comment]
change DFIntTaskSchedulerTargetFps to 0 and get default roblox fps unlocker

**Comment by Soupplex** [comment]
I want UNLIMITED fps unlocker NOT the limited.

**Comment by Soupplex** [comment]
Anyways

**Comment by Soupplex** [comment]
I see no solution to this problem,so i will close this issue.
