### ISSUE TITLE
[TalkToMe]

### ISSUE THREAD

**Issue by ucjd** [NoobLikesThis/roblox-fflags#12]
### What do you want to say to me?

does the hitbox expander even work? like can you try getting some info on it or something like how does it work, how much bigger does it make the hitboxes, does changing the values make it bigger or can u make it smaller? if it makes the hitbox bigger even if only a little bit just let me know, id like you to look into it and tell me if you can find anything 🙏

**Comment by NoobLikesThis** [comment]
i dont even have a hitbox expander in this list, real hitbox doesnt say its an expander dumbass

**Comment by NoobLikesThis** [comment]
@ucjd if u have a dc acc, can u join my dc server rq i cant get the fflags so can u get them for me?
