### ISSUE TITLE
FFlagRenamePassesAndGearToSubscriptionsAndPasses

### ISSUE THREAD

**Issue by genocydr** [NoobLikesThis/roblox-fflags#8]
thefrenchguy4 did NOT find FFlagRenamePassesAndGearToSubscriptionsAndPasses, I found it back in my peak of fflags in may and posted it in my now nuked server.

**Comment by NoobLikesThis** [comment]
genocydr? is that u??

**Comment by genocydr** [comment]
![image](https://github.com/user-attachments/assets/c64e79de-57a6-4a0e-a35a-4608a9a2aca9)
6es vro

**Comment by NoobLikesThis** [comment]
damn

**Comment by NoobLikesThis** [comment]
dang

**Comment by genocydr** [comment]
> still need evidence that u found it first

g my server was fucking nuked

**Comment by NoobLikesThis** [comment]
ss?

**Comment by genocydr** [comment]
> ss?

and you need to add my credit for 
{
    "FStringAXCategories": "ClassicShirts.ClassicTShirts.ClassicPants"
}

**Comment by genocydr** [comment]
> > > ss?
> > 
> > 
> > and you need to add my credit for { "FStringAXCategories": "ClassicShirts.ClassicTShirts.ClassicPants" }
> 
> talk to https://github.com/d44df016fe28bc8d5974/rbxflags abt it

https://discord.com/channels/1099468797410283540/1248716204731011143/1248716385388073060
